Repository milieuinfo/webcomponent-vl-ui-input-group, pull requests merged in 2019-09, with the labels that each got.

#21 UIG-218
  vl-input-group.src.js
Labels: maintenance

#22 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#8 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#28 Update dependency vl-ui-input-field to v1.0.11
  package-lock.json
  package.json
Labels: dependencies

#27 Update dependency vl-ui-icon to v2.0.11
  package-lock.json
  package.json
Labels: dependencies

#26 Update dependency vl-ui-form-message to v2.2.6
  package-lock.json
  package.json
Labels: dependencies

#25 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency vl-ui-button to v1.1.9
  package-lock.json
  package.json
Labels: dependencies

#23 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#29 Update package-lock
  package-lock.json
Labels: bug

#32 Update dependency vl-ui-icon to v2.0.12
  package-lock.json
  package.json
Labels: dependencies

#31 Update dependency vl-ui-button to v1.1.10
  package-lock.json
  package.json
Labels: dependencies

#33 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#35 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
