Repository milieuinfo/webcomponent-vl-ui-input-group, pull requests merged in 2020-01, with the labels that each got.

#58 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#54 Initiele opzet
  .mocharc.js
  bamboo-specs/bamboo.yml
  index.js
  package-lock.json
  package.json
  test/docker-compose.yml
  test/e2e/input-group.test.js
  test/e2e/pages/vl-input-group.page.js
  test/unit/vl-input-group.test.html
  test/wct.docker.conf.json
Labels: chore

#59 Test opzet
  package-lock.json
  package.json
Labels: bugfix

#60 Update gitignore
  .gitignore
  test/e2e/components/vl-input-group.js
Labels: bugfix

#61 Overbodig NPM release import scripts verwijderd
  package.json
  vl-input-group.js
Labels: maintenance

#63 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#62 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#64 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#65 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
